const DEFAULT_LIMIT = 20;
const DEFAULT_ITEMS_LIMIT = 12;
const MAX_LIMIT = Number.MAX_SAFE_INTEGER;

const DEFAULT_PARAMS = {
  page: 1,
  limit: DEFAULT_LIMIT,
};

export { DEFAULT_LIMIT, MAX_LIMIT, DEFAULT_PARAMS, DEFAULT_ITEMS_LIMIT };
